version: '3.1'
services:
  db:
    image: mysql
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2  # Specify the desired fixed IP address

  back:
    depends_on:
      - db
    image: mokhtar1234/achat-devops:latest
    container_name: back
    restart: on-failure
    ports:
      - "6868:8089"
    stdin_open: true
    tty: true
    environment:
      SPRING_PROFILES_ACTIVE: prod,actuator
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3  # Specify a different fixed IP address

  front:
    image: mokhtar1234/achat-front:latest
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      mynetwork:
        ipv4_address: 172.18.0.4  # Specify a different fixed IP address

volumes:
  mysql_data:
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
