version: '3.1'
services:
  db:
    image: mysql
    container_name: mon_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: achatdb
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2  # Specify the desired fixed IP address

  back:
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - "8083:8089"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3  # Specify a different fixed IP address

  front:
    image: ihebkraiem/achatfrontend:latest
    ports:
      - "8090:80"
    depends_on:
      - back
    networks:
      mynetwork:
        ipv4_address: 172.18.0.4  # Specify a different fixed IP address

volumes:
  db:
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16