version: '3.8'
services:
  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: achatdb
    networks:
      - mynetwork

  back:
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - 6868:8082
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - mynetwork
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - DATABASE_URL=jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - DATABASE_DRIVER=org.hibernate.dialect.MySQL5InnoDBDialect

  front:
    image: mokhtar1234/achat-front:latest
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - mynetwork
volumes:
  db:
networks:
  mynetwork: