version: '3'
services:
  achat:
    image: achat:latest
    restart: on-failure
    ports:
      - '8089:8089'
    depends_on:
      - mysql
    networks:
      - mynetwork
    volumes:
      - .m2:/root/.m2
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: emtiez
      MYSQL_DATABASE: achatdb
      MYSQL_USER: emtiez
      MYSQL_PASSWORD: emtiez
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  mynetwork:
    driver: bridge
volumes:
  mysql-data:
  .m2:



