version: '3.8'
services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - mynetwork

  back:
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - 6868:8082
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - mynetwork

  front:
    image: mokhtar1234/achat-front:latest
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - mynetwork
volumes:
  db:
networks:
  mynetwork: