version: '3.1'
services:
    db:
        image: mysql:5.7
        container_name: database
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: achatdb
        networks:
            - mynetwork

    backend:
        image: bileljemai/achat-devops:latest
        container_name: backend
        restart: on-failure
        ports:
            - "7070:8089"
        depends_on:
            - db
        networks:
            - mynetwork

    frontend:
        image: bileljemai/front:latest
        ports:
            - "80:80"
        depends_on:
            - backend
        networks:
            - mynetwork

volumes:
    mysql_data:

networks:
    mynetwork:
        driver: bridge
