version: '3.1'
services:
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: achatdb
      MYSQL_PASSWORD: null
    networks:
      - mynetwork

  back:
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - "6868:8082"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - mynetwork


  front:
    image: mokhtar1234/achat-front:latest
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - mynetwork
volumes:
  db:
networks:
  mynetwork: